services:
  db:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=test

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "6831:6831/udp"
      - "14268:14268"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_DEFAULT_USER: test
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_net

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 1234

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./config/local/prometheus:/etc/prometheus
      
  grafana:
    image: grafana/grafana
    ports:
      - 9091:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./config/local/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./config/local/grafana/dashboards:/etc/grafana/provisioning/dashboards

networks:
  vault_init:
    driver: bridge
  rabbitmq_net:
    driver: bridge
