{
 "title": "You App Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Default statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests rate for all requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(endpoint, method) (rate(your_app_http_response_total{endpoint!=\"/metrics\"}[$__rate_interval])) > 0",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Success responses counter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(floor(sum by(endpoint, method) (increase(your_app_http_response_total{status=~\"200|201|302\", endpoint!=\"/metrics\"}[$__range]))) > 0)",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Bad responses counter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(floor(sum by(endpoint, method) (increase(your_app_http_response_total{status=~\"4..|5..\", endpoint!=\"/metrics\"}[$__range])))) > 0",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(your_app_http_response_time_seconds_bucket{endpoint!=\"/metrics\"}[$__rate_interval])))",
     "legendFormat": "request time"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Success requests rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "p99" ] } },
   "targets": [
    {
     "expr": "rate(your_app_http_response_total{status=~\"2..\", endpoint!=\"/metrics\"}[$__range])",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Bad requests rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "p99" ] } },
   "targets": [
    {
     "expr": "rate(your_app_http_response_total{status=~\"4..|5..\"}[$__range])",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Unauthorized requests rate (401, 403)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "p99" ] } },
   "targets": [
    {
     "expr": "rate(your_app_http_response_total{status=~\"403|401\"}[$__range])",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests rates for bad requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(endpoint, status, method) (rate(your_app_http_response_total{status=~\"4..|5..\"}[$__rate_interval])) > 0",
     "legendFormat": "{{status}} {{method}} {{endpoint}}"
    }
   ]
  }
 ]
}